version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: pokequiz
      MYSQL_USER: pokeuser
      MYSQL_PASSWORD: StrongPassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ./PokemonQuizAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # API connects to the mariadb container on the internal container port (3306)
      ConnectionStrings__Default: "Server=mariadb;Port=3306;Database=pokequiz;User=pokeuser;Password=StrongPassword"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      - mariadb
      - redis
    ports:
      - "5168:80"

volumes:
  db-data:
